### ISSUE TITLE
ヘッダー　Metaタグの整備

### ISSUE THREAD

**Issue by holmes1825** [holmes1825/twin_engine#23]
GA, Meta, OGP, Favicon

**Comment by holmes1825** [comment]
`<head><script async="" src="//www.google-analytics.com/analytics.js"></script><script id="twitter-wjs" src="http://platform.twitter.com/widgets.js"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-92083704-2', 'auto');
  ga('send', 'pageview');

</script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="google-site-verification" content="ADEDibi0LZTg3NYqQSJBuwvpLlv0Zx4CJFUkzy2ITcA">
<meta http-equiv="Content-Style-Type" content="text/css">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta name="robots" content="noarchive">
<meta name="robots" content="index,follow">
<meta name="description" content="TWIN ENGINE Inc. | アニメーション映画の企画プロダクション、株式会社ツインエンジンのホームページです。">
<meta name="keywords" content="ツインエンジン,アニメ,ノイタミナ,スタジオコロリド,ポレットのイス,山本幸治,石田祐康,天王洲アイル">
<meta name="viewport" content="width=1200">
<meta property="og:title" content="株式会社ツインエンジン">
<meta property="og:url" content="http://www.twinengine.jp/">
<meta property="og:image" content="http://www.twinengine.jp/img/v2engine_3.png">
<meta property="og:description" content="TWIN ENGINE Inc. | アニメーション映画の企画プロダクション、株式会社ツインエンジンのホームページです。">
<meta property="og:site_name" content="株式会社ツインエンジン">
<link href="top.css" rel="stylesheet" type="text/css">
<title>株式会社ツインエンジンホームページ</title>
`

**Comment by hiromichi-yokochi** [comment]
https://docs.google.com/spreadsheets/d/1XtUaJo1It-Y9R4fBZpjljLYiSuQvNAzMVjDX6dbD54Y/edit?usp=sharing

ここにまとめました
