### ISSUE TITLE
トップページのスライダー関連

### ISSUE THREAD

**Issue by holmes1825** [holmes1825/twin_engine#24]

**Comment by hiromichi-yokochi** [comment]
保留で

**Comment by hiromichi-yokochi** [comment]
鈴木さん確認中

**Comment by suzuki-p** [comment]
[TEスライド.pptx](https://github.com/holmes1825/twin_engine/files/901872/TE.pptx)

スライドはこの3枚でいきましょう

**Comment by holmes1825** [comment]
https://github.com/holmes1825/twin_engine/commit/f3c7daa60dd68fab76a0cbf1d2b52663eabca8fb
DONEです

**Comment by holmes1825** [comment]
採用のリンク先が未設定

**Comment by suzuki-p** [comment]
採用のバナー　気持ち色を変えて欲しい
